name: spotify

version: 1.0.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  assets_audio_player: ^3.1.1
  cached_network_image: ^3.3.1
  desktop_window: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
